baseURL = "https://heaphopper.github.io/portfolio"
title = "Welcome"
theme = "gokarna"
languageCode = "en-us"
defaultContentLanguage = "en"

# Enable syntax highlighting (optional)
pygmentsStyle = "monokai"

# Parameters specific to Gokarna Theme
[params]
  description = "Honestly, its just where I dump my crazy ideas XD"
  avatarURL = "/images/avatar.jpeg"  # Add this later
  ShowBackToTopButton = true
  footer = "Tzvi E. Nir"

[[params.socialIcons]]
name = "github"
url = "https://github.com/heaphopper"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/tzvi-eliezer-nir-abb836170"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    pre = "<span data-feather='user'></span>"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 4

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 5

  [[menu.main]]
    identifier = "github"
    url = "https://github.com/heaphopper"
    weight = 6
    pre = "<span data-feather='github'></span>"
    post = ""

